# Generated by Django 4.0.1 on 2022-09-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone_user_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
