# Generated by Django 4.0.1 on 2022-10-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tguser_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgProcessedUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.IntegerField(verbose_name='ID последнего обработанного сообщения')),
            ],
        ),
    ]
